require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "vendor/**/*"

######## Style ########
# redirect_to xxx and return のイディオムを維持したい
Style/AndOr:
  EnforcedStyle: conditionals

# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false

# Class名の::を許可する default: nested
Style/ClassAndModuleChildren:
  Enabled: false

# ドキュメントの無い public class を許可する
Style/Documentation:
  Enabled: false

# 文字リテラルのイミュータブル宣言を無視（freezeになるのはRuby3以降）
Style/FrozenStringLiteralComment:
  Enabled: false

# Lambda処理をすべてアロー演算子で表記する（デフォルトは1行: アロー演算子, 複数行: Lambda）
Style/Lambda:
  EnforcedStyle: literal

# 1_000_000 と区切り文字が 2 個以上必要になる場合のみ _ 区切りを必須にする
Style/NumericLiterals:
  MinDigits: 7

# 条件式の方を意識させたい場合には後置の if/unless を使わない方が分かりやすい
Style/IfUnlessModifier:
  Enabled: false

######## Metrics ########
# メソッドのサイズ
Metrics/AbcSize:
  Max: 24

# 1メソッドの長さ
Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/**/*" # migrateファイルは除外

# Classの長さ
Metrics/ClassLength:
  Max: 120

# GemのOrderしない
Bundler/OrderedGems:
  Enabled: false

# Capybaraのfind_by_**が反映しないようにspec除外
Rails/DynamicFindBy:
  Exclude:
    - "spec/**/*"

######## Layout ########
# 行の長さを変更
Layout/LineLength:
  IgnoredPatterns: ['\A#'] # コメントは除外
  Exclude:
    - "db/fixtures/**/*" # seedファイルは除外
    - "db/migrate/**/*" # migrateファイルは除外
    - "spec/**/*" # specファイルは除外

# 自動生成ファイル除外
Metrics/BlockLength:
  Exclude:
    - "lib/tasks/auto_annotate_models.rake"
    - "spec/**/*"
    - "Guardfile"
Style/BlockComments:
  Exclude:
    - "spec/spec_helper.rb"
Style/MixinUsage:
  Exclude:
    - "bin/**"
Layout/HashAlignment:
  Exclude:
    - "lib/tasks/auto_annotate_models.rake"
Rails/RakeEnvironment:
  Exclude:
    - "lib/tasks/auto_annotate_models.rake"
