name: Linters

on: [push]

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run rubocop
        run: bundle exec rubocop
      - name: Run slim lint
        if: always()
        run: bundle exec slim-lint app/views/
      - name: Run scss lint
        if: always()
        run: bundle exec scss-lint app/assets/stylesheets/
