name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DATABASE_HOST: 127.0.0.1
      DATABASE_USER: ci_user
      DATABASE_PASSWORD: ci_password
      TZ: Asia/Tokyo
    services:
      db:
        image: postgres:12.4
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_DB: instant_code_review_test
          POSTGRES_USER: ci_user
          POSTGRES_PASSWORD: ci_password

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: yarn install
      - name: Set up database
        run: bin/rails db:schema:load --trace
      - name: Run rspec
        run: bundle exec rspec
